# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "node1" do |app|
    app.vm.box = "bento/ubuntu-16.04"
    app.vm.network "private_network", ip: "192.168.33.11"
    app.vm.hostname = "node1"
    app.vm.provider "virtualbox" do |v|
      v.memory = 512
      v.cpus = 1
    end
  end
  config.vm.define "node2" do |app|
    app.vm.box = "bento/ubuntu-16.04"
    app.vm.network "private_network", ip: "192.168.33.12"
    app.vm.hostname = "node2"
    app.vm.provider "virtualbox" do |v|
      v.memory = 512
      v.cpus = 1
    end
  end
end
